#!/bin/bash
#
# tree_visualizer: a convenience script to launch the visualizer code that's
# included with joshua.
#
# Author: Jonny Weese <jonny@cs.jhu.edu>

# Die if any variables are unset.
set -o nounset
# Die if any statement returns non-true.
set -o errexit

# Get variables from the command line.
SOURCE=$1
REFERENCE=$2
N_BEST=$3

LIB=$JOSHUA/lib

# Build up the classpath: first the Joshua files,
VISUALIZATION_CLASSPATH=$JOSHUA/bin
# the Java Unified Network Graph library API,
VISUALIZATION_CLASSPATH="$VISUALIZATION_CLASSPATH:$LIB/jung-api-2.0.jar"
# the JUNG Algorithms,
VISUALIZATION_CLASSPATH="$VISUALIZATION_CLASSPATH:$LIB/jung-algorithms-2.0.jar"
# the JUNG graph implementations,
VISUALIZATION_CLASSPATH="$VISUALIZATION_CLASSPATH:$LIB/jung-graph-impl-2.0.jar"
# and JUNG graph-visualization code.
VISUALIZATION_CLASSPATH="$VISUALIZATION_CLASSPATH:$LIB/jung-visualization-2.0.jar"

java -cp $VISUALIZATION_CLASSPATH \
	joshua.ui.tree_visualizer.browser.Browser \
	$SOURCE \
	$REFERENCE \
	$N_BEST
